import * as fs from "node:fs";
import * as path from "node:path";
import { buildWireApplyValidationModuleSource } from "./apply-validation-build.ts";
import { buildSchemaModuleSource } from "./schema-build.ts";
import { createExtractorProgram } from "./extract.ts";
import {
  checkCache,
  isTsBuiltinLibFile,
  writeCacheMetadata,
  type CacheLocationOptions,
} from "./cache.ts";

// The generated module's `compileWireEntryFragment`/`compileConstraintsFn`
// output (type-ir/src/compile.ts) emits typed guards — each entry's `check`
// is cast to `(value: unknown) => value is T` — so the file typechecks clean
// under `strict` with no `@ts-nocheck`, and a consumer narrows `.value` off
// `.kind === "ok"` instead of reading `unknown`.
const GENERATED_HEADER = "// @generated by @rhi-zone/fractal-api-tree — do not edit\n";

const USAGE = `Usage: fractal-api-tree <command> [options]

Commands:
  build <entry> -o <output>          Build the applyValidation module (skip if cached)
                                      — every applyValidation(key, tree, protocol?)
                                      call site (an omitted protocol resolves to
                                      "identity" — see docs/design/wire-profiles-
                                      and-staged-validation.md)
  watch <entry> -o <output>          Rebuild on change
  check <entry> -o <output>          Verify output is up to date; exit 1 if stale
  build-schema <entry> -o <output> --tree-id <id>   Build the JSON-Schema module (skip if cached)
  watch-schema <entry> -o <output> --tree-id <id>   Rebuild on change
  check-schema <entry> -o <output> --tree-id <id>   Verify output is up to date; exit 1 if stale

Options:
  -o, --output <path>     Output file path
  --tree-id <id>          Which exported tree in <entry> to build (required for
                           the -schema commands — the tree's own exported
                           binding name; a factory function's name, a const's
                           identifier, or "default" for a bare default export)
  --force                 Rebuild even if the cache says up to date
  --cache-file <path>     Cache metadata file (default: <output>.cache.json)
  --cache-dir <path>      Directory to pool cache metadata in (overridden by --cache-file)
  --help                  Show this help text

Caching: build/watch/check (and their -schema counterparts) skip regeneration
when a content-addressed cache (entry file + every source file its
extraction reads + TypeScript/fractal-type-ir versions) says nothing
relevant changed — see @rhi-zone/fractal-api-tree/cache's module doc for the
full design. --force bypasses it unconditionally.
`;

type ParsedArgs = {
  positional: string[];
  output?: string;
  treeId?: string;
  force: boolean;
  help: boolean;
  cacheFile?: string;
  cacheDir?: string;
};

function parseArgs(argv: string[]): ParsedArgs {
  const positional: string[] = [];
  let output: string | undefined;
  let treeId: string | undefined;
  let force = false;
  let help = false;
  let cacheFile: string | undefined;
  let cacheDir: string | undefined;

  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];
    if (arg === "-o" || arg === "--output") {
      output = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--tree-id") {
      treeId = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--force") {
      force = true;
      i++;
      continue;
    }
    if (arg === "--cache-file") {
      cacheFile = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--cache-dir") {
      cacheDir = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      help = true;
      i++;
      continue;
    }
    if (arg !== undefined) positional.push(arg);
    i++;
  }

  return {
    positional,
    force,
    help,
    ...(output !== undefined ? { output } : {}),
    ...(treeId !== undefined ? { treeId } : {}),
    ...(cacheFile !== undefined ? { cacheFile } : {}),
    ...(cacheDir !== undefined ? { cacheDir } : {}),
  };
}

function withHeader(source: string): string {
  return GENERATED_HEADER + source;
}

function ensureParentDir(outFile: string): void {
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
}

function requireOutput(output: string | undefined): string {
  if (output === undefined) {
    throw new Error("missing required flag: -o/--output <output>");
  }
  return output;
}

function requireEntry(positional: string[]): string {
  const entry = positional[0];
  if (entry === undefined) {
    throw new Error("missing required argument: <entry>");
  }
  return entry;
}

function requireTreeId(treeId: string | undefined): string {
  if (treeId === undefined) {
    throw new Error("missing required flag: --tree-id <id>");
  }
  return treeId;
}

function cacheOptsOf(args: ParsedArgs): CacheLocationOptions {
  return {
    ...(args.cacheFile !== undefined ? { cacheFile: args.cacheFile } : {}),
    ...(args.cacheDir !== undefined ? { cacheDir: args.cacheDir } : {}),
    // Folds `--tree-id` into the cache key (see cache.ts's
    // `CacheLocationOptions.buildOptionsKey` doc comment and
    // docs/current/repo-audit-2026-08-20.md §1.3): without this,
    // `build-schema e -o out --tree-id A` then `--tree-id B` was a Tier-1
    // hit serving tree A's stale artifact as "up to date" for tree B. `""`
    // for the non-schema commands (`args.treeId` is always undefined there),
    // preserving their existing cache key exactly.
    buildOptionsKey: args.treeId ?? "",
  };
}

/** One artifact kind's build function — `buildWireApplyValidationModuleSource`
 * (with its extra `outFile`-anchored import-resolution option) for
 * `build`/`watch`/`check`, `buildSchemaModuleSource` for the `-schema`
 * commands. Both take `(entryFile, program)` once curried here, so
 * `runBuild`/`runCheck`/`runWatch` below are shared across both artifact
 * kinds — same cache contract, same CLI plumbing, no second divergent code
 * path. An entry file with no `applyValidation` call sites builds to the
 * pre-codegen stub (`applyValidationStubSource`, apply-validation-build.ts),
 * following the same "compiles and runs before codegen has ever produced
 * anything" convention `build`/`watch`/`check` always had.
 *
 * `build`/`watch`/`check` run every `applyValidation(key, tree, protocol?)`
 * call site, whether or not its source spells a `protocol` (an omitted one
 * resolves to `"identity"` — see `extractWireApplyValidationTypeRefs`'s doc
 * comment, apply-validation-build.ts). `shouldShare`/defs structural sharing
 * is not exposed as a CLI flag here. */
type ArtifactBuilder = (
  entryFile: string,
  outFile: string,
  program: import("typescript").Program,
) => string;

const VALIDATOR_BUILDER: ArtifactBuilder = (entryFile, outFile, program) =>
  buildWireApplyValidationModuleSource(entryFile, { outFile, program });

/** Curries `treeId` (mandatory on `buildSchemaModuleSource` — see tree.ts's
 * `extractToolSchemas` doc comment) into an `ArtifactBuilder`, so
 * `runBuild`/`runCheck`/`runWatch` stay shared across both artifact kinds
 * without VALIDATOR_BUILDER also needing a `treeId` it has no use for. */
function schemaBuilderFor(treeId: string): ArtifactBuilder {
  return (entryFile, _outFile, program) => buildSchemaModuleSource(entryFile, treeId, program);
}

function runBuild(
  builder: ArtifactBuilder,
  entryFile: string,
  outFile: string,
  args: ParsedArgs,
): void {
  const cacheOpts = cacheOptsOf(args);
  if (!args.force) {
    const check = checkCache(entryFile, outFile, cacheOpts);
    if (check.hit) {
      process.stdout.write(`up to date: ${outFile} (cache hit)\n`);
      return;
    }
  }
  const start = performance.now();
  const program = createExtractorProgram(entryFile);
  const source = withHeader(builder(entryFile, outFile, program));
  ensureParentDir(outFile);
  fs.writeFileSync(outFile, source);
  writeCacheMetadata(entryFile, outFile, program, source, cacheOpts);
  const elapsed = performance.now() - start;
  process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`);
}

function runCheck(
  builder: ArtifactBuilder,
  entryFile: string,
  outFile: string,
  args: ParsedArgs,
): void {
  const cacheOpts = cacheOptsOf(args);
  if (!args.force) {
    const cached = checkCache(entryFile, outFile, cacheOpts);
    if (cached.hit) {
      process.stdout.write(`up to date: ${outFile} (cache hit)\n`);
      return;
    }
  }
  const program = createExtractorProgram(entryFile);
  const source = withHeader(builder(entryFile, outFile, program));
  const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined;
  if (existing === source) {
    // Refresh cache metadata now that we've already paid for building the
    // Program and the fresh source — a from-scratch `check` (no cache file,
    // or a prior miss) that confirms the output is still correct previously
    // wrote nothing, so every subsequent `check` repaid the exact same full
    // cost again (audit §6#5). Only done on the up-to-date branch: writing
    // metadata on the stale branch below would record a fresh outputHash
    // for content that was never actually written to `outFile`.
    writeCacheMetadata(entryFile, outFile, program, source, cacheOpts);
    process.stdout.write(`up to date: ${outFile}\n`);
    return;
  }
  process.stderr.write(`stale: ${outFile} needs regeneration\n`);
  process.exit(1);
}

/** Every directory containing a file in `program`'s tracked closure (its own
 * per-file `.ts` sources, excluding TypeScript's bundled lib files — same
 * exclusion `writeCacheMetadata` uses) — the set of directories `runWatch`
 * needs a watcher on for the closure to actually be covered, instead of just
 * the entry file's own (non-recursive) directory (audit §6#4: a `watch` that
 * only watches `path.dirname(entryFile)` non-recursively misses edits to
 * transitively imported files outside that one directory — a subdirectory, a
 * sibling package, anything — even though the cache tracks the full
 * closure). */
function watchDirsOf(program: import("typescript").Program): Set<string> {
  const dirs = new Set<string>();
  for (const sourceFile of program.getSourceFiles()) {
    if (isTsBuiltinLibFile(sourceFile.fileName)) continue;
    dirs.add(path.dirname(sourceFile.fileName));
  }
  return dirs;
}

function runWatch(
  builder: ArtifactBuilder,
  entryFile: string,
  outFile: string,
  args: ParsedArgs,
): void {
  runBuild(builder, entryFile, outFile, args);

  const cacheOpts = cacheOptsOf(args);
  let timer: NodeJS.Timeout | undefined;
  let watchers: fs.FSWatcher[] = [];

  const scheduleRebuild = () => {
    if (timer !== undefined) clearTimeout(timer);
    timer = setTimeout(rebuild, 150);
  };

  /** (Re-)watch exactly `dirs`, tearing down any previous watcher set first —
   * called after every rebuild since the closure itself (and so the set of
   * directories worth watching) can change between builds (a new import
   * added/removed). Each directory is watched non-recursively — watching the
   * closure's own directories directly, rather than relying on platform-
   * dependent `recursive: true` support, covers the "wrong scope" half of
   * §6#4 without a portability dependency. */
  const setWatchers = (dirs: ReadonlySet<string>) => {
    for (const watcher of watchers) watcher.close();
    watchers = [...dirs].map((dir) =>
      fs.watch(dir, (_event, filename) => {
        if (filename === null || !filename.endsWith(".ts")) return;
        scheduleRebuild();
      }),
    );
  };

  const rebuild = () => {
    const start = performance.now();
    const program = createExtractorProgram(entryFile);
    const source = withHeader(builder(entryFile, outFile, program));
    const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined;
    setWatchers(watchDirsOf(program));
    if (existing === source) {
      writeCacheMetadata(entryFile, outFile, program, source, cacheOpts);
      process.stdout.write("no changes\n");
      return;
    }
    ensureParentDir(outFile);
    fs.writeFileSync(outFile, source);
    writeCacheMetadata(entryFile, outFile, program, source, cacheOpts);
    const elapsed = performance.now() - start;
    process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`);
  };

  // Initial watch set: a fresh Program over `entryFile`, same as `rebuild`
  // would build — `runBuild` above may have taken the cache-hit path (no
  // Program built), so this can't reuse its result; the extra Program build
  // is a one-time startup cost for a long-running dev command.
  setWatchers(watchDirsOf(createExtractorProgram(entryFile)));

  const shutdown = () => {
    if (timer !== undefined) clearTimeout(timer);
    for (const watcher of watchers) watcher.close();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
}

function main(): void {
  const argv = process.argv.slice(2);
  const isHelpFlag = argv[0] === "--help" || argv[0] === "-h";
  const command = isHelpFlag ? undefined : argv[0];
  const args = parseArgs(argv.slice(1));

  if (command === undefined || args.help) {
    process.stdout.write(USAGE);
    process.exit(argv.length === 0 ? 1 : 0);
  }

  switch (command) {
    case "build": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runBuild(VALIDATOR_BUILDER, entry, output, args);
      break;
    }
    case "watch": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runWatch(VALIDATOR_BUILDER, entry, output, args);
      break;
    }
    case "check": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runCheck(VALIDATOR_BUILDER, entry, output, args);
      break;
    }
    case "build-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runBuild(schemaBuilderFor(treeId), entry, output, args);
      break;
    }
    case "watch-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runWatch(schemaBuilderFor(treeId), entry, output, args);
      break;
    }
    case "check-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runCheck(schemaBuilderFor(treeId), entry, output, args);
      break;
    }
    default:
      process.stderr.write(`unknown command: ${command}\n\n${USAGE}`);
      process.exit(1);
  }
}

try {
  main();
} catch (err: unknown) {
  const msg = err instanceof Error ? err.message : String(err);
  process.stderr.write(`error: ${msg}\n`);
  process.exit(1);
}
