import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import type ts from "typescript";
import {
  buildWireApplyValidationModuleCached,
  buildWireApplyValidationModuleSourceIncremental,
  wireApplyValidationBuildOptionsKey,
} from "./apply-validation-build.ts";
import {
  buildSchemaModuleCached,
  buildSchemaModuleSourceIncremental,
  schemaBuildOptionsKey,
} from "./schema-build.ts";
import { createExtractorProgram } from "./extract.ts";
import {
  checkCache,
  isTsBuiltinLibFile,
  readCarryForwardState,
  writeCacheMetadata,
  type CachedBuildOutcome,
  type CacheFileShapeV3,
  type CacheLocationOptions,
} from "./cache.ts";

// The generated module's `compileWireEntryFragment`/`compileConstraintsFn`
// output (type-ir/src/compile.ts) emits typed guards — each entry's `check`
// is cast to `(value: unknown) => value is T` — so the file typechecks clean
// under `strict` with no `@ts-nocheck`, and a consumer narrows `.value` off
// `.kind === "ok"` instead of reading `unknown`.
const GENERATED_HEADER = "// @generated by @rhi-zone/fractal-api-tree — do not edit\n";

const USAGE = `Usage: fractal-api-tree <command> [options]

Commands:
  build <entry> -o <output>          Build the applyValidation module (skip if cached)
                                      — every applyValidation(key, tree, protocol?)
                                      call site (an omitted protocol resolves to
                                      "identity" — see docs/design/wire-profiles-
                                      and-staged-validation.md)
  watch <entry> -o <output>          Rebuild on change
  check <entry> -o <output>          Verify output is up to date; exit 1 if stale
  build-schema <entry> -o <output> --tree-id <id>   Build the JSON-Schema module (skip if cached)
  watch-schema <entry> -o <output> --tree-id <id>   Rebuild on change
  check-schema <entry> -o <output> --tree-id <id>   Verify output is up to date; exit 1 if stale

Options:
  -o, --output <path>     Output file path
  --tree-id <id>          Which exported tree in <entry> to build (required for
                           the -schema commands — the tree's own exported
                           binding name; a factory function's name, a const's
                           identifier, or "default" for a bare default export)
  --force                 Rebuild even if the cache says up to date
  --cache-file <path>     Cache metadata file (default: <output>.cache.json)
  --cache-dir <path>      Directory to pool cache metadata in (overridden by --cache-file)
  --help                  Show this help text

Caching: build/watch/check (and their -schema counterparts) skip regeneration
when a content-addressed cache (entry file + every source file its
extraction reads + its resolved tsconfig/compilerOptions +
TypeScript/fractal-type-ir/fractal-api-tree versions + --tree-id) says
nothing relevant changed — see @rhi-zone/fractal-api-tree/cache's module doc
for the full design. build/watch/check now all go through the library's
Tier-2 (leaf-level incremental) builders, so a Tier-1 miss still only
recompiles the leaves whose own fingerprint actually changed, carried
forward via the cache file's leafFingerprints/leafArtifacts. --force bypasses
the cache unconditionally.
`;

type ParsedArgs = {
  positional: string[];
  output?: string;
  treeId?: string;
  force: boolean;
  help: boolean;
  cacheFile?: string;
  cacheDir?: string;
};

function parseArgs(argv: string[]): ParsedArgs {
  const positional: string[] = [];
  let output: string | undefined;
  let treeId: string | undefined;
  let force = false;
  let help = false;
  let cacheFile: string | undefined;
  let cacheDir: string | undefined;

  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];
    if (arg === "-o" || arg === "--output") {
      output = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--tree-id") {
      treeId = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--force") {
      force = true;
      i++;
      continue;
    }
    if (arg === "--cache-file") {
      cacheFile = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--cache-dir") {
      cacheDir = argv[i + 1];
      i += 2;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      help = true;
      i++;
      continue;
    }
    if (arg !== undefined) positional.push(arg);
    i++;
  }

  return {
    positional,
    force,
    help,
    ...(output !== undefined ? { output } : {}),
    ...(treeId !== undefined ? { treeId } : {}),
    ...(cacheFile !== undefined ? { cacheFile } : {}),
    ...(cacheDir !== undefined ? { cacheDir } : {}),
  };
}

/** Formats `source` through the repo's `oxfmt` (via `bunx`, so it resolves
 * from whichever workspace package's node_modules the check is invoked from
 * — same binary `bun run format`/`format:check` use at the repo root) the
 * same way the committed artifact was formatted before it was committed.
 * `runCheck` needs this because it compares in-memory generator output
 * against a committed file that went through `oxfmt --write .` after being
 * generated — comparing raw generator bytes against that formatted file
 * fails unconditionally on style alone, regardless of real drift. `outFile`
 * is passed only as `--stdin-filepath` so oxfmt infers the right parser
 * (TypeScript) and any path-based formatting config; the file itself is
 * never read or written. */
function formatWithOxfmt(source: string, outFile: string): string {
  const result = spawnSync("bunx", ["oxfmt", `--stdin-filepath=${outFile}`], {
    input: source,
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    const stderr = result.stderr ?? "";
    throw new Error(`oxfmt failed formatting ${outFile} for comparison: ${stderr}`);
  }
  return result.stdout;
}

function ensureParentDir(outFile: string): void {
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
}

function requireOutput(output: string | undefined): string {
  if (output === undefined) {
    throw new Error("missing required flag: -o/--output <output>");
  }
  return output;
}

function requireEntry(positional: string[]): string {
  const entry = positional[0];
  if (entry === undefined) {
    throw new Error("missing required argument: <entry>");
  }
  return entry;
}

function requireTreeId(treeId: string | undefined): string {
  if (treeId === undefined) {
    throw new Error("missing required flag: --tree-id <id>");
  }
  return treeId;
}

/** `--cache-file`/`--cache-dir` only — the cache key's `buildOptionsKey` half
 * is now computed by each `ArtifactKind`'s own `buildOptionsKey` (mirroring
 * exactly what its `cached` builder computes internally), not assembled here
 * — see `ArtifactKind`'s doc comment. */
function cacheLocationOptsOf(args: ParsedArgs): CacheLocationOptions {
  return {
    ...(args.cacheFile !== undefined ? { cacheFile: args.cacheFile } : {}),
    ...(args.cacheDir !== undefined ? { cacheDir: args.cacheDir } : {}),
  };
}

/** Prior Tier-2 state as `readCarryForwardState` returns it — passed straight
 * through to an `ArtifactKind.incremental` call. */
type PriorState = Pick<
  CacheFileShapeV3,
  "leafFingerprints" | "leafArtifacts" | "defNamesFingerprint"
>;

/** One Tier-2 incremental build's result, narrowed to what `runCheck` needs
 * to pass on to `writeCacheMetadata`'s `leafData` — a subset of
 * `WireApplyValidationIncrementalResult`/`SchemaIncrementalResult` (both
 * carry more fields — `changedLeaves`, and the validator's own
 * `defNamesFingerprint` — that this shape's callers don't need). */
type IncrementalBuildResult = {
  readonly source: string;
  readonly leafFingerprints: Record<string, string>;
  readonly leafArtifacts: Record<string, unknown>;
  readonly defNamesFingerprint?: string;
};

/** One artifact kind's build machinery, both tiers: `cached` is the
 * library's `build*Cached` wrapper (Tier 1 `checkCache` gate + Tier 2
 * leaf-level incremental build + `writeCacheMetadata`, all in one call) —
 * what `runBuild`/`runWatch` use directly, now that the CLI engages Tier 2
 * for real instead of calling the plain non-incremental builders and writing
 * cache metadata with empty `leafFingerprints`/`leafArtifacts` (audit §6#1).
 * `incremental` is the lower-level Tier-2 build function alone (no Tier-1
 * gate, no metadata write) — `runCheck` needs this instead of `cached`
 * because it writes its OWN cache metadata keyed to the oxfmt-*formatted*
 * source (see `runCheck`'s doc comment for why), not the raw bytes `cached`
 * would record. `buildOptionsKey` is the exact formula `cached` folds
 * `--tree-id`/header/etc into (`wireApplyValidationBuildOptionsKey`/
 * `schemaBuildOptionsKey`, exported by the two build modules for this
 * reason) — `runCheck` needs it too, to compute a `checkCache`/
 * `writeCacheMetadata` call that agrees with what `cached` would have
 * recorded, without duplicating (and risking drifting from) that formula. */
type ArtifactKind = {
  readonly cached: (
    entryFile: string,
    outFile: string,
    opts: CacheLocationOptions & { readonly force?: boolean; readonly header?: string },
  ) => CachedBuildOutcome<string>;
  readonly incremental: (
    entryFile: string,
    outFile: string,
    program: ts.Program,
    prior: PriorState | undefined,
  ) => IncrementalBuildResult;
  readonly buildOptionsKey: (header: string) => string;
};

const VALIDATOR_KIND: ArtifactKind = {
  cached: (entryFile, outFile, opts) => buildWireApplyValidationModuleCached(entryFile, outFile, opts),
  incremental: (entryFile, outFile, program, prior) => {
    const built = buildWireApplyValidationModuleSourceIncremental(entryFile, {
      outFile,
      program,
      ...(prior !== undefined ? { prior } : {}),
    });
    return {
      source: built.source,
      leafFingerprints: built.leafFingerprints,
      leafArtifacts: built.leafArtifacts,
      defNamesFingerprint: built.defNamesFingerprint,
    };
  },
  buildOptionsKey: (header) => wireApplyValidationBuildOptionsKey({ header }),
};

/** Curries `treeId` (mandatory on the schema builders — see tree.ts's
 * `extractToolSchemas` doc comment) into an `ArtifactKind`, so
 * `runBuild`/`runCheck`/`runWatch` stay shared across both artifact kinds
 * without `VALIDATOR_KIND` also needing a `treeId` it has no use for. */
function schemaKindFor(treeId: string): ArtifactKind {
  return {
    cached: (entryFile, outFile, opts) => buildSchemaModuleCached(entryFile, treeId, outFile, opts),
    incremental: (entryFile, _outFile, program, prior) => {
      const built = buildSchemaModuleSourceIncremental(entryFile, treeId, program, prior);
      return {
        source: built.source,
        leafFingerprints: built.leafFingerprints,
        leafArtifacts: built.leafArtifacts,
      };
    },
    buildOptionsKey: (header) => schemaBuildOptionsKey(treeId, { header }),
  };
}

function runBuild(kind: ArtifactKind, entryFile: string, outFile: string, args: ParsedArgs): void {
  const start = performance.now();
  const outcome = kind.cached(entryFile, outFile, {
    ...cacheLocationOptsOf(args),
    force: args.force,
    header: GENERATED_HEADER,
  });
  if (outcome.status === "hit") {
    process.stdout.write(`up to date: ${outFile} (cache hit)\n`);
    return;
  }
  ensureParentDir(outFile);
  fs.writeFileSync(outFile, outcome.result);
  const elapsed = performance.now() - start;
  process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`);
}

/**
 * `check` builds through the SAME Tier-2 incremental function `runBuild`
 * uses (`kind.incremental`, carry-forward included via
 * `readCarryForwardState`) but does NOT use `kind.cached` end to end,
 * because `check`'s own `writeCacheMetadata` call needs to record the
 * oxfmt-*formatted* bytes, not the raw ones `kind.incremental`/`cached`
 * produce — the committed artifact went through `oxfmt --write .` after
 * `build` wrote it (build itself emits raw, unformatted output), so diffing
 * raw generator bytes against it would fail on style alone even with zero
 * real drift (audit §7#5), and recording metadata keyed to the wrong (raw)
 * bytes would immediately re-mismatch `outFile`'s real (formatted) bytes on
 * the very next check. `cacheOpts.buildOptionsKey` is computed via
 * `kind.buildOptionsKey` — the exact formula `kind.cached` uses internally —
 * so this function's own `checkCache`/`writeCacheMetadata` calls agree with
 * what a `build`/`watch` run would have recorded.
 */
function runCheck(kind: ArtifactKind, entryFile: string, outFile: string, args: ParsedArgs): void {
  const cacheOpts: CacheLocationOptions = {
    ...cacheLocationOptsOf(args),
    buildOptionsKey: kind.buildOptionsKey(GENERATED_HEADER),
  };
  if (!args.force) {
    const cached = checkCache(entryFile, outFile, cacheOpts);
    if (cached.hit) {
      process.stdout.write(`up to date: ${outFile} (cache hit)\n`);
      return;
    }
  }
  const program = createExtractorProgram(entryFile);
  const prior = readCarryForwardState(entryFile, outFile, cacheOpts);
  const built = kind.incremental(entryFile, outFile, program, prior);
  const source = GENERATED_HEADER + built.source;
  // Compare the *formatted* generator output against the committed file —
  // see this function's doc comment above.
  const formattedSource = formatWithOxfmt(source, outFile);
  const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined;
  if (existing === formattedSource) {
    // Refresh cache metadata now that we've already paid for building the
    // Program and the fresh source — a from-scratch `check` (no cache file,
    // or a prior miss) that confirms the output is still correct previously
    // wrote nothing, so every subsequent `check` repaid the exact same full
    // cost again (audit §6#5). Only done on the up-to-date branch: writing
    // metadata on the stale branch below would record a fresh outputHash
    // for content that was never actually written to `outFile`. Hashed as
    // `formattedSource`, not raw `source` — see this function's doc comment.
    // `leafData` is now populated (audit §6#1) — previously `check` (like
    // `build`/`watch`) called `writeCacheMetadata` with no `leafData` at
    // all, so a cache file `check` last touched carried empty
    // `leafFingerprints`/`leafArtifacts` regardless of how much Tier-2 state
    // a prior `build` had accumulated.
    writeCacheMetadata(entryFile, outFile, program, formattedSource, cacheOpts, undefined, {
      leafFingerprints: built.leafFingerprints,
      leafArtifacts: built.leafArtifacts,
      ...(built.defNamesFingerprint !== undefined
        ? { defNamesFingerprint: built.defNamesFingerprint }
        : {}),
    });
    process.stdout.write(`up to date: ${outFile}\n`);
    return;
  }
  process.stderr.write(`stale: ${outFile} needs regeneration\n`);
  process.exit(1);
}

/** Every directory containing a file in `program`'s tracked closure (its own
 * per-file `.ts` sources, excluding TypeScript's bundled lib files — same
 * exclusion `writeCacheMetadata` uses) — the set of directories `runWatch`
 * needs a watcher on for the closure to actually be covered, instead of just
 * the entry file's own (non-recursive) directory (audit §6#4: a `watch` that
 * only watches `path.dirname(entryFile)` non-recursively misses edits to
 * transitively imported files outside that one directory — a subdirectory, a
 * sibling package, anything — even though the cache tracks the full
 * closure). */
function watchDirsOf(program: ts.Program): Set<string> {
  const dirs = new Set<string>();
  for (const sourceFile of program.getSourceFiles()) {
    if (isTsBuiltinLibFile(sourceFile.fileName)) continue;
    dirs.add(path.dirname(sourceFile.fileName));
  }
  return dirs;
}

function runWatch(kind: ArtifactKind, entryFile: string, outFile: string, args: ParsedArgs): void {
  runBuild(kind, entryFile, outFile, args);

  const cacheLocationOpts = cacheLocationOptsOf(args);
  let timer: NodeJS.Timeout | undefined;
  let watchers: fs.FSWatcher[] = [];

  const scheduleRebuild = () => {
    if (timer !== undefined) clearTimeout(timer);
    timer = setTimeout(rebuild, 150);
  };

  /** (Re-)watch exactly `dirs`, tearing down any previous watcher set first —
   * called after every rebuild since the closure itself (and so the set of
   * directories worth watching) can change between builds (a new import
   * added/removed). Each directory is watched non-recursively — watching the
   * closure's own directories directly, rather than relying on platform-
   * dependent `recursive: true` support, covers the "wrong scope" half of
   * §6#4 without a portability dependency. */
  const setWatchers = (dirs: ReadonlySet<string>) => {
    for (const watcher of watchers) watcher.close();
    watchers = [...dirs].map((dir) =>
      fs.watch(dir, (_event, filename) => {
        if (filename === null || !filename.endsWith(".ts")) return;
        scheduleRebuild();
      }),
    );
  };

  /** Every trigger goes through `kind.cached` — the Tier-1 `checkCache` gate
   * it runs internally means a spurious/no-op fs event (nothing in the
   * tracked closure actually changed) now resolves to a fast hit instead of
   * unconditionally rebuilding and re-extracting on every filesystem event,
   * as the pre-Tier-2 CLI did. `force` is never passed here — only the
   * initial `runBuild` call above honors `--force`; once watching, staying
   * on the cache's own change-detection is the point. */
  const rebuild = () => {
    const start = performance.now();
    const outcome = kind.cached(entryFile, outFile, { ...cacheLocationOpts, header: GENERATED_HEADER });
    if (outcome.status === "hit") {
      process.stdout.write("no changes\n");
      return;
    }
    setWatchers(watchDirsOf(outcome.program));
    const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined;
    if (existing === outcome.result) {
      // Tracked-file content moved (Tier-1 miss) but the emitted bytes
      // didn't (e.g. a comment-only edit) — skip the write to avoid an
      // needless mtime bump; `kind.cached` already wrote fresh metadata for
      // the new tracked-file state.
      process.stdout.write("no changes\n");
      return;
    }
    ensureParentDir(outFile);
    fs.writeFileSync(outFile, outcome.result);
    const elapsed = performance.now() - start;
    process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`);
  };

  // Initial watch set: a fresh Program over `entryFile`, same as `rebuild`
  // would build — `runBuild` above may have taken the cache-hit path (no
  // Program built), so this can't reuse its result; the extra Program build
  // is a one-time startup cost for a long-running dev command.
  setWatchers(watchDirsOf(createExtractorProgram(entryFile)));

  const shutdown = () => {
    if (timer !== undefined) clearTimeout(timer);
    for (const watcher of watchers) watcher.close();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
}

function main(): void {
  const argv = process.argv.slice(2);
  const isHelpFlag = argv[0] === "--help" || argv[0] === "-h";
  const command = isHelpFlag ? undefined : argv[0];
  const args = parseArgs(argv.slice(1));

  if (command === undefined || args.help) {
    process.stdout.write(USAGE);
    process.exit(argv.length === 0 ? 1 : 0);
  }

  switch (command) {
    case "build": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runBuild(VALIDATOR_KIND, entry, output, args);
      break;
    }
    case "watch": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runWatch(VALIDATOR_KIND, entry, output, args);
      break;
    }
    case "check": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      runCheck(VALIDATOR_KIND, entry, output, args);
      break;
    }
    case "build-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runBuild(schemaKindFor(treeId), entry, output, args);
      break;
    }
    case "watch-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runWatch(schemaKindFor(treeId), entry, output, args);
      break;
    }
    case "check-schema": {
      const entry = requireEntry(args.positional);
      const output = requireOutput(args.output);
      const treeId = requireTreeId(args.treeId);
      runCheck(schemaKindFor(treeId), entry, output, args);
      break;
    }
    default:
      process.stderr.write(`unknown command: ${command}\n\n${USAGE}`);
      process.exit(1);
  }
}

try {
  main();
} catch (err: unknown) {
  const msg = err instanceof Error ? err.message : String(err);
  process.stderr.write(`error: ${msg}\n`);
  process.exit(1);
}
