import * as fs from "node:fs"
import * as path from "node:path"
import { buildApplyValidationModuleSource } from "./apply-validation-build.ts"
import { buildSchemaModuleSource } from "./schema-build.ts"
import { createExtractorProgram } from "./extract.ts"
import { checkCache, writeCacheMetadata, type CacheLocationOptions } from "./cache.ts"

// No `@ts-nocheck`: `compileValidatorModule` (type-ir/src/compile.ts) emits
// typed guards — each entry's `check` is cast to `(value: unknown) => value
// is T`, so the file typechecks clean under `strict`, and a consumer narrows
// `.value` off `.kind === "ok"` instead of reading `unknown`.
const GENERATED_HEADER = "// @generated by @rhi-zone/fractal-api-tree — do not edit\n"

const USAGE = `Usage: fractal-api-tree <command> [options]

Commands:
  build <entry> -o <output>          Build the applyValidation module (skip if cached)
  watch <entry> -o <output>          Rebuild on change
  check <entry> -o <output>          Verify output is up to date; exit 1 if stale
  build-schema <entry> -o <output>   Build the JSON-Schema module (skip if cached)
  watch-schema <entry> -o <output>   Rebuild on change
  check-schema <entry> -o <output>   Verify output is up to date; exit 1 if stale

Options:
  -o, --output <path>     Output file path
  --force                 Rebuild even if the cache says up to date
  --cache-file <path>     Cache metadata file (default: <output>.cache.json)
  --cache-dir <path>      Directory to pool cache metadata in (overridden by --cache-file)
  --help                  Show this help text

Caching: build/watch/check (and their -schema counterparts) skip regeneration
when a content-addressed cache (entry file + every source file its
extraction reads + TypeScript/fractal-type-ir versions) says nothing
relevant changed — see @rhi-zone/fractal-api-tree/cache's module doc for the
full design. --force bypasses it unconditionally.
`

type ParsedArgs = {
  positional: string[]
  output?: string
  force: boolean
  help: boolean
  cacheFile?: string
  cacheDir?: string
}

function parseArgs(argv: string[]): ParsedArgs {
  const positional: string[] = []
  let output: string | undefined
  let force = false
  let help = false
  let cacheFile: string | undefined
  let cacheDir: string | undefined

  let i = 0
  while (i < argv.length) {
    const arg = argv[i]
    if (arg === "-o" || arg === "--output") {
      output = argv[i + 1]
      i += 2
      continue
    }
    if (arg === "--force") {
      force = true
      i++
      continue
    }
    if (arg === "--cache-file") {
      cacheFile = argv[i + 1]
      i += 2
      continue
    }
    if (arg === "--cache-dir") {
      cacheDir = argv[i + 1]
      i += 2
      continue
    }
    if (arg === "--help" || arg === "-h") {
      help = true
      i++
      continue
    }
    if (arg !== undefined) positional.push(arg)
    i++
  }

  return {
    positional,
    force,
    help,
    ...(output !== undefined ? { output } : {}),
    ...(cacheFile !== undefined ? { cacheFile } : {}),
    ...(cacheDir !== undefined ? { cacheDir } : {}),
  }
}

function withHeader(source: string): string {
  return GENERATED_HEADER + source
}

function ensureParentDir(outFile: string): void {
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
}

function requireOutput(output: string | undefined): string {
  if (output === undefined) {
    throw new Error("missing required flag: -o/--output <output>")
  }
  return output
}

function requireEntry(positional: string[]): string {
  const entry = positional[0]
  if (entry === undefined) {
    throw new Error("missing required argument: <entry>")
  }
  return entry
}

function cacheOptsOf(args: ParsedArgs): CacheLocationOptions {
  return {
    ...(args.cacheFile !== undefined ? { cacheFile: args.cacheFile } : {}),
    ...(args.cacheDir !== undefined ? { cacheDir: args.cacheDir } : {}),
  }
}

/** One artifact kind's build function — `buildApplyValidationModuleSource`
 * (with its extra `outFile`-anchored import-resolution option) for
 * `build`/`watch`/`check`, `buildSchemaModuleSource` for the `-schema`
 * commands. Both take `(entryFile, program)` once curried here, so
 * `runBuild`/`runCheck`/`runWatch` below are shared across both artifact
 * kinds — same cache contract, same CLI plumbing, no second divergent code
 * path. An entry file with no `applyValidation(key, tree)` call sites builds
 * to the pre-codegen stub (`applyValidationStubSource`,
 * apply-validation-build.ts) — same "compiles and runs before codegen has
 * ever produced anything" convention `build`/`watch`/`check` always had. */
type ArtifactBuilder = (entryFile: string, outFile: string, program: import("typescript").Program) => string

const VALIDATOR_BUILDER: ArtifactBuilder = (entryFile, outFile, program) =>
  buildApplyValidationModuleSource(entryFile, { outFile, program })

const SCHEMA_BUILDER: ArtifactBuilder = (entryFile, _outFile, program) =>
  buildSchemaModuleSource(entryFile, program)

function runBuild(
  builder: ArtifactBuilder,
  entryFile: string,
  outFile: string,
  args: ParsedArgs,
): void {
  const cacheOpts = cacheOptsOf(args)
  if (!args.force) {
    const check = checkCache(entryFile, outFile, cacheOpts)
    if (check.hit) {
      process.stdout.write(`up to date: ${outFile} (cache hit)\n`)
      return
    }
  }
  const start = performance.now()
  const program = createExtractorProgram(entryFile)
  const source = withHeader(builder(entryFile, outFile, program))
  ensureParentDir(outFile)
  fs.writeFileSync(outFile, source)
  writeCacheMetadata(entryFile, outFile, program, source, cacheOpts)
  const elapsed = performance.now() - start
  process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`)
}

function runCheck(builder: ArtifactBuilder, entryFile: string, outFile: string, args: ParsedArgs): void {
  const cacheOpts = cacheOptsOf(args)
  if (!args.force) {
    const cached = checkCache(entryFile, outFile, cacheOpts)
    if (cached.hit) {
      process.stdout.write(`up to date: ${outFile} (cache hit)\n`)
      return
    }
  }
  const program = createExtractorProgram(entryFile)
  const source = withHeader(builder(entryFile, outFile, program))
  const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined
  if (existing === source) {
    process.stdout.write(`up to date: ${outFile}\n`)
    return
  }
  process.stderr.write(`stale: ${outFile} needs regeneration\n`)
  process.exit(1)
}

function runWatch(builder: ArtifactBuilder, entryFile: string, outFile: string, args: ParsedArgs): void {
  runBuild(builder, entryFile, outFile, args)

  const watchDir = path.dirname(entryFile)
  const cacheOpts = cacheOptsOf(args)
  let timer: NodeJS.Timeout | undefined

  const rebuild = () => {
    const start = performance.now()
    const program = createExtractorProgram(entryFile)
    const source = withHeader(builder(entryFile, outFile, program))
    const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined
    if (existing === source) {
      writeCacheMetadata(entryFile, outFile, program, source, cacheOpts)
      process.stdout.write("no changes\n")
      return
    }
    ensureParentDir(outFile)
    fs.writeFileSync(outFile, source)
    writeCacheMetadata(entryFile, outFile, program, source, cacheOpts)
    const elapsed = performance.now() - start
    process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`)
  }

  const watcher = fs.watch(watchDir, (_event, filename) => {
    if (filename === null || !filename.endsWith(".ts")) return
    if (timer !== undefined) clearTimeout(timer)
    timer = setTimeout(rebuild, 150)
  })

  const shutdown = () => {
    if (timer !== undefined) clearTimeout(timer)
    watcher.close()
    process.exit(0)
  }
  process.on("SIGINT", shutdown)
}

function main(): void {
  const argv = process.argv.slice(2)
  const isHelpFlag = argv[0] === "--help" || argv[0] === "-h"
  const command = isHelpFlag ? undefined : argv[0]
  const args = parseArgs(argv.slice(1))

  if (command === undefined || args.help) {
    process.stdout.write(USAGE)
    process.exit(argv.length === 0 ? 1 : 0)
  }

  switch (command) {
    case "build": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runBuild(VALIDATOR_BUILDER, entry, output, args)
      break
    }
    case "watch": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runWatch(VALIDATOR_BUILDER, entry, output, args)
      break
    }
    case "check": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runCheck(VALIDATOR_BUILDER, entry, output, args)
      break
    }
    case "build-schema": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runBuild(SCHEMA_BUILDER, entry, output, args)
      break
    }
    case "watch-schema": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runWatch(SCHEMA_BUILDER, entry, output, args)
      break
    }
    case "check-schema": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runCheck(SCHEMA_BUILDER, entry, output, args)
      break
    }
    default:
      process.stderr.write(`unknown command: ${command}\n\n${USAGE}`)
      process.exit(1)
  }
}

try {
  main()
} catch (err: unknown) {
  const msg = err instanceof Error ? err.message : String(err)
  process.stderr.write(`error: ${msg}\n`)
  process.exit(1)
}
