// packages/api-tree/src/schema-build.ts — @rhi-zone/fractal-api-tree
//
// SCHEMA-ARTIFACT BUILD ORCHESTRATOR: the sibling of build.ts's
// `buildValidatorModuleSource`/`writeValidatorModule`, emitting a standalone
// TS module that exports the `SchemaMap` `extractToolSchemas` (tree.ts)
// produces — one per entry file, same conventions (generated-file header,
// `--check` drift-detection semantics, cache behavior) as the validator
// module, so the two artifacts never diverge into separately-maintained
// codegen paths.
//
// Why a SEPARATE artifact from the validator module, not folded into it:
// `compileValidatorModule` (type-ir) emits COMPILED functions
// (`check`/`errors`/`parse`) derived from each leaf's TypeRef — those need
// zero runtime dependencies, which is exactly its point. A `SchemaMap` is
// plain JSON-Schema DATA (no functions to compile), consumed by
// `toOpenApi`'s `schemas` option (http-api-projector/openapi.ts) to avoid
// paying `extractToolSchemas`'s own `ts.Program` cost at doc-build/request
// time. Emitting it as its own generated module — rather than adding a
// second export to the validator module — keeps each artifact's consumer
// importing only what it needs (a validator-wiring call site never needs
// JSON-Schema data; an OpenAPI-doc build never needs compiled validators),
// and keeps `--check` drift detection scoped: a change that only affects
// schema shape (e.g. a JSDoc description edit) doesn't need to touch the
// validator module's generated bytes, and vice versa.
//
// Emission format: plain `JSON.stringify(schemas, null, 2)` — a `SchemaMap`
// is exactly the kind of value JSON.stringify already renders correctly
// (nested objects/arrays/strings/numbers/booleans, `$comment` punts
// included as regular string values), so there's no need for
// `compileValidatorModule`'s template-per-shape-kind codegen machinery here
// at all — that machinery exists because compiled validator FUNCTIONS need
// custom control flow per shape; a schema is just data.

import type ts from "typescript"
import { createExtractorProgram } from "./extract.ts"
import { extractToolSchemas, type SchemaMap } from "./tree.ts"
import { withCache, type CacheLocationOptions, type CachedBuildOutcome } from "./cache.ts"

/**
 * Extract every leaf op's derived JSON-Schema from `entryFile` and render it
 * as a standalone TS module source string: `export const schemas:
 * SchemaMap`. `program`, when given, reuses a pre-built `ts.Program` — same
 * batching rationale as `buildValidatorModuleSource`'s own `program`
 * parameter (build.ts): a caller building both the validator module and the
 * schema artifact for the same batch of entry files shares ONE Program
 * across both passes, rather than building it twice (once per artifact
 * kind) or twice per entry.
 */
export function buildSchemaModuleSource(entryFile: string, program?: ts.Program): string {
  const programOpt = program === undefined ? {} : { program }
  const schemas = extractToolSchemas(entryFile, programOpt)
  return renderSchemaModule(schemas)
}

/** Render a `SchemaMap` value to TS module source — split out from
 * `buildSchemaModuleSource` so `buildSchemaModuleCached`'s cache-hit path
 * never needs to call it, and so a caller with an already-extracted
 * `SchemaMap` (e.g. reusing one it also fed to `toOpenApi`'s `schemas`
 * option in-process) can render it without re-extracting. */
function renderSchemaModule(schemas: SchemaMap): string {
  const lines = [
    'import type { SchemaMap } from "@rhi-zone/fractal-api-tree/tree"',
    "",
    `export const schemas: SchemaMap = ${JSON.stringify(schemas, null, 2)}`,
    "",
  ]
  return lines.join("\n")
}

/**
 * Build the schema module for `entryFile` and write it to `outFile`.
 */
export async function writeSchemaModule(entryFile: string, outFile: string): Promise<void> {
  await Bun.write(outFile, buildSchemaModuleSource(entryFile))
}

// ============================================================================
// Cached variants — same `withCache` (cache.ts) the validator module's
// `buildValidatorModuleCached`/`writeValidatorModuleCached` use, so a schema
// artifact's cache metadata lives under its OWN `outFile` (a distinct file
// from the validator module's), tracked independently: touching only a
// schema-relevant input (there are none, in practice, that a validator
// build wouldn't also care about — both walk the same tree) still keys off
// each artifact's own recorded closure/output hash, never cross-invalidates
// the other artifact's cache entry.
// ============================================================================

/**
 * `buildSchemaModuleSource`, cached — see build.ts's
 * `buildValidatorModuleCached` for the shared cache-hit/-miss contract
 * (`withCache`, cache.ts) this mirrors exactly, just for the schema
 * artifact instead of the validator module.
 */
export function buildSchemaModuleCached(
  entryFile: string,
  outFile: string,
  options?: {
    readonly program?: ts.Program
    readonly force?: boolean
  } & CacheLocationOptions,
): CachedBuildOutcome<string> {
  return withCache(
    entryFile,
    outFile,
    (program) => buildSchemaModuleSource(entryFile, program),
    { ...options, createProgram: createExtractorProgram },
  )
}

/**
 * `writeSchemaModule`, cached: only writes `outFile` (and updates cache
 * metadata) when `buildSchemaModuleCached` actually built something.
 */
export async function writeSchemaModuleCached(
  entryFile: string,
  outFile: string,
  options?: {
    readonly program?: ts.Program
    readonly force?: boolean
  } & CacheLocationOptions,
): Promise<CachedBuildOutcome<string>> {
  const outcome = buildSchemaModuleCached(entryFile, outFile, options)
  if (outcome.status === "built") await Bun.write(outFile, outcome.result)
  return outcome
}
