// GENERATED by @rhi-zone/fractal-codegen — typed server handler signatures.
// Source: OpenAPI "Todo API" v1.0.0. DO NOT EDIT.
// Concrete types only — zero type-level computation (no Client<App> walk).

import type { Handler } from "@rhi-zone/fractal-core";

/** Handler signature for `GET /todos`. */
export type GetTodos = Handler<{}>;

/** Handler signature for `POST /todos`. */
export type PostTodos = Handler<{}>;

/** Handler signature for `POST /todos/{id}/done`. */
export type PostTodosIdDone = Handler<{
    id: string;
  }>;

/** Handler signature for `GET /todos/{id}`. */
export type GetTodosId = Handler<{
    id: string;
  }>;

/** Handler signature for `GET /me`. */
export type GetMe = Handler<{}>;

/** Handler signature for `GET /health`. */
export type GetHealth = Handler<{}>;

/** Handler signature for `GET /events`. */
export type GetEvents = Handler<{}>;

/** Handler signature for `GET /favicon`. */
export type GetFavicon = Handler<{}>;
