import * as fs from "node:fs"
import * as path from "node:path"
import { buildValidatorModuleSource, stubValidatorModuleSource } from "./build.ts"

// `@ts-nocheck`: the emitted body comes straight out of TypeBox's
// `TypeCompiler.Code()` (compile.ts) — untyped-by-construction JS (implicit
// `any` params, a widened `kind: string` rather than the `"ok" | "err"`
// literal union `Validator`'s `Result` expects). It's a build artifact, not
// hand-authored source; consumers rely on `ValidatorMap`'s type at the
// import boundary, not on this file typechecking under the consumer's
// (possibly `strict`) tsconfig.
const GENERATED_HEADER = "// @generated by @rhi-zone/fractal-codegen — do not edit\n// @ts-nocheck\n"

const USAGE = `Usage: fractal-codegen <command> [options]

Commands:
  build <entry> -o <output>   Build the validator module (skip if up to date)
  watch <entry> -o <output>   Rebuild on change
  stub -o <output>            Write an empty stub validator module
  check <entry> -o <output>   Verify output is up to date; exit 1 if stale

Options:
  -o, --output <path>   Output file path
  --force                Rebuild even if output is newer than entry
  --help                 Show this help text
`

type ParsedArgs = {
  positional: string[]
  output?: string
  force: boolean
  help: boolean
}

function parseArgs(argv: string[]): ParsedArgs {
  const positional: string[] = []
  let output: string | undefined
  let force = false
  let help = false

  let i = 0
  while (i < argv.length) {
    const arg = argv[i]
    if (arg === "-o" || arg === "--output") {
      output = argv[i + 1]
      i += 2
      continue
    }
    if (arg === "--force") {
      force = true
      i++
      continue
    }
    if (arg === "--help" || arg === "-h") {
      help = true
      i++
      continue
    }
    if (arg !== undefined) positional.push(arg)
    i++
  }

  return output === undefined
    ? { positional, force, help }
    : { positional, output, force, help }
}

function withHeader(source: string): string {
  return GENERATED_HEADER + source
}

function ensureParentDir(outFile: string): void {
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
}

function requireOutput(output: string | undefined): string {
  if (output === undefined) {
    throw new Error("missing required flag: -o/--output <output>")
  }
  return output
}

function requireEntry(positional: string[]): string {
  const entry = positional[0]
  if (entry === undefined) {
    throw new Error("missing required argument: <entry>")
  }
  return entry
}

function isUpToDate(entryFile: string, outFile: string): boolean {
  if (!fs.existsSync(outFile)) return false
  const entryMtime = fs.statSync(entryFile).mtimeMs
  const outMtime = fs.statSync(outFile).mtimeMs
  return outMtime > entryMtime
}

function runBuild(entryFile: string, outFile: string, force: boolean): void {
  if (!force && isUpToDate(entryFile, outFile)) {
    process.stdout.write(`up to date: ${outFile}\n`)
    return
  }
  const start = performance.now()
  const source = withHeader(buildValidatorModuleSource(entryFile))
  ensureParentDir(outFile)
  fs.writeFileSync(outFile, source)
  const elapsed = performance.now() - start
  process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`)
}

function runStub(outFile: string): void {
  const source = withHeader(stubValidatorModuleSource())
  ensureParentDir(outFile)
  fs.writeFileSync(outFile, source)
  process.stdout.write(`wrote stub ${outFile}\n`)
}

function runCheck(entryFile: string, outFile: string): void {
  const source = withHeader(buildValidatorModuleSource(entryFile))
  const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined
  if (existing === source) {
    process.stdout.write(`up to date: ${outFile}\n`)
    return
  }
  process.stderr.write(`stale: ${outFile} needs regeneration\n`)
  process.exit(1)
}

function runWatch(entryFile: string, outFile: string, force: boolean): void {
  runBuild(entryFile, outFile, force)

  const watchDir = path.dirname(entryFile)
  let timer: NodeJS.Timeout | undefined

  const rebuild = () => {
    const start = performance.now()
    const source = withHeader(buildValidatorModuleSource(entryFile))
    const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : undefined
    if (existing === source) {
      process.stdout.write("no changes\n")
      return
    }
    ensureParentDir(outFile)
    fs.writeFileSync(outFile, source)
    const elapsed = performance.now() - start
    process.stdout.write(`built ${outFile} in ${elapsed.toFixed(1)}ms\n`)
  }

  const watcher = fs.watch(watchDir, (_event, filename) => {
    if (filename === null || !filename.endsWith(".ts")) return
    if (timer !== undefined) clearTimeout(timer)
    timer = setTimeout(rebuild, 150)
  })

  const shutdown = () => {
    if (timer !== undefined) clearTimeout(timer)
    watcher.close()
    process.exit(0)
  }
  process.on("SIGINT", shutdown)
}

function main(): void {
  const argv = process.argv.slice(2)
  const isHelpFlag = argv[0] === "--help" || argv[0] === "-h"
  const command = isHelpFlag ? undefined : argv[0]
  const args = parseArgs(argv.slice(1))

  if (command === undefined || args.help) {
    process.stdout.write(USAGE)
    process.exit(argv.length === 0 ? 1 : 0)
  }

  switch (command) {
    case "build": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runBuild(entry, output, args.force)
      break
    }
    case "watch": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runWatch(entry, output, args.force)
      break
    }
    case "stub": {
      const output = requireOutput(args.output)
      runStub(output)
      break
    }
    case "check": {
      const entry = requireEntry(args.positional)
      const output = requireOutput(args.output)
      runCheck(entry, output)
      break
    }
    default:
      process.stderr.write(`unknown command: ${command}\n\n${USAGE}`)
      process.exit(1)
  }
}

try {
  main()
} catch (err: unknown) {
  const msg = err instanceof Error ? err.message : String(err)
  process.stderr.write(`error: ${msg}\n`)
  process.exit(1)
}
