// packages/http-framework-projector/src/express.test.ts — Express router codegen tests
//
// Three kinds of coverage, mirroring http-api-projector's codegen.test.ts:
//   1. Structural: assert the generated source string has the expected
//      shape (imports, path syntax, Handlers type, factory function) for a
//      self-contained fixture tree.
//   2. Eval (end-to-end): write the generated source to a temp file, import
//      it as a real module, mount the returned `Router` into a real
//      `express()` app, and drive real HTTP requests at it via `supertest`-
//      free raw `fetch` against a listening server, confirming the emitted
//      code works as an actual Express router, not just matching expected
//      text.
//   3. HttpRoute-driven (no Node): `generateExpressRouter(route, schemas)`
//      called directly, exercising the core entry point standalone.

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import express from "express";
import type { Express, NextFunction, Request, Response, Router } from "express";
import type { Server } from "node:http";
import { api as api_, op } from "@rhi-zone/fractal-api-tree/node";
import { extractToolSchemas } from "@rhi-zone/fractal-api-tree/tree";
import type { SchemaMap } from "@rhi-zone/fractal-api-tree/tree";
import { http } from "@rhi-zone/fractal-http-api-projector/verbs";
import { httpProjection } from "@rhi-zone/fractal-http-api-projector/dx";
import { generateExpressRouter, generateExpressRouterFromNode } from "./express.ts";

// ============================================================================
// Fixture tree — books list/add (static), plus a per-book fallback subtree
// with a co-located read/replace/remove trio, matching the shape
// examples/library-api/src/tree.ts uses: real path-param and co-location
// coverage.
// ============================================================================

type Book = { readonly id: string; readonly title: string; readonly author: string };

function makeStore() {
  const store = new Map<string, Book>();
  let seq = 0;

  const listBooks = op((input: { readonly author?: string }): Book[] => {
    const all = [...store.values()];
    return input?.author !== undefined ? all.filter((b) => b.author === input.author) : all;
  }, http.get);

  const addBook = op((input: { readonly title: string; readonly author: string }): Book => {
    const id = `book-${++seq}`;
    const book: Book = { id, ...input };
    store.set(id, book);
    return book;
  }, http.post);

  const readBook = op(
    (input: { readonly bookId: string }): Book => {
      const book = store.get(input.bookId);
      if (book === undefined) throw new Error(`Not Found: ${input.bookId}`);
      return book;
    },
    http.get,
    http.moveTo(".."),
  );

  const replaceBook = op(
    (input: { readonly bookId: string; readonly title: string; readonly author: string }): Book => {
      const book: Book = { id: input.bookId, title: input.title, author: input.author };
      store.set(input.bookId, book);
      return book;
    },
    http.put,
    http.moveTo(".."),
  );

  const removeBook = op(
    (input: { readonly bookId: string }): { readonly deleted: boolean } => {
      return { deleted: store.delete(input.bookId) };
    },
    http.delete,
    http.moveTo(".."),
  );

  const bookItemNode = api_({ read: readBook, replace: replaceBook, remove: removeBook });
  const booksNode = api_(
    { list: listBooks, add: addBook },
    { fallback: { name: "bookId", subtree: bookItemNode } },
  );
  const tree = api_({ books: booksNode });

  return { tree, store };
}

const { tree } = makeStore();
const treePath = new URL("./__fixtures__/express-tree.ts", import.meta.url).pathname;

let source: string;
let schemas: SchemaMap;

beforeAll(() => {
  schemas = extractToolSchemas(treePath);
  source = generateExpressRouterFromNode(tree, schemas, { routerName: "Books" });
});

// ============================================================================
// 1. Structural assertions
// ============================================================================

describe("generateExpressRouterFromNode — structure", () => {
  it("emits a generated/eject header", () => {
    expect(source).toMatch(/^\/\/ @generated by @rhi-zone\/fractal-http-framework-projector/);
    expect(source).toContain("Eject model");
  });

  it("imports Router (value) and types from express", () => {
    expect(source).toContain('import { Router } from "express"');
    expect(source).toContain("NextFunction");
  });

  it("emits real Express path syntax (:bookId, not {bookId})", () => {
    expect(source).toContain('"/books/:bookId"');
    expect(source).not.toContain("{bookId}");
  });

  it("emits GET for list, POST for add, GET/PUT/DELETE co-located at :bookId", () => {
    // list/add have no `http.moveTo` directive, so (mirroring
    // examples/library-api's own listBooks/addBook) they land at their own
    // path segment — /books/list, /books/add — not collapsed onto /books.
    expect(source).toMatch(/router\.get\("\/books\/list",/);
    expect(source).toMatch(/router\.post\("\/books\/add",/);
    expect(source).toMatch(/router\.get\("\/books\/:bookId",/);
    expect(source).toMatch(/router\.put\("\/books\/:bookId",/);
    expect(source).toMatch(/router\.delete\("\/books\/:bookId",/);
  });

  it("emits the BooksHandlers type and createBooksRouter factory", () => {
    expect(source).toContain("export type BooksHandlers");
    expect(source).toContain("export function createBooksRouter(handlers: BooksHandlers)");
  });

  it("emits Input/Output type aliases from the schema map", () => {
    expect(source).toContain("export type BooksAddInput");
    expect(source).toContain("export type BooksAddOutput");
  });

  it("dispatches to the accumulated dotted handler path, not a flattened name", () => {
    expect(source).toContain("await handlers.books.list(input)");
    expect(source).toContain("await handlers.books.add(input)");
    expect(source).toContain("await handlers.books.bookId.read(input)");
    expect(source).toContain("await handlers.books.bookId.replace(input)");
    expect(source).toContain("await handlers.books.bookId.remove(input)");
  });

  it("wraps handler calls in try/catch and forwards errors via next(err)", () => {
    expect(source).toContain("} catch (err) {");
    expect(source).toContain("next(err)");
  });
});

// ============================================================================
// 2. HttpRoute-driven entry point (no Node) — degraded naming
// ============================================================================

describe("generateExpressRouter — HttpRoute-driven, no Node", () => {
  it("still produces a mountable router with degraded (lowercased-verb) member names", () => {
    const route = httpProjection(tree);
    const routeSource = generateExpressRouter(route, schemas, { routerName: "Degraded" });
    expect(routeSource).toContain("export function createDegradedRouter");
    // Co-located verbs at /books/:bookId degrade to their lowercased HTTP verb
    // as the member name (no Node available to recover "read"/"replace"/"remove").
    expect(routeSource).toMatch(/await handlers\.books\.bookId\.get\(input\)/);
    expect(routeSource).toMatch(/await handlers\.books\.bookId\.put\(input\)/);
    expect(routeSource).toMatch(/await handlers\.books\.bookId\.delete\(input\)/);
  });
});

// ============================================================================
// 3. Eval: real Express app, real HTTP requests
// ============================================================================

describe("generated Express router — real app, real requests", () => {
  let tmpDir: string | undefined;
  let server: Server | undefined;
  let baseUrl: string;

  beforeAll(async () => {
    const { tree: evalTree, store } = makeStore();
    const evalSchemas = extractToolSchemas(treePath);
    const evalSource = generateExpressRouterFromNode(evalTree, evalSchemas, {
      routerName: "Books",
    });

    // Written under the package's own `.local-data/` (gitignored, see root
    // .gitignore) rather than the OS tmpdir: the generated file `import`s
    // "express", and Node/Bun module resolution walks up from the importing
    // file's directory looking for `node_modules` — a path outside this
    // package tree would never find the package-local `node_modules/express`
    // bun's isolated linker installed.
    const localDataDir = join(import.meta.dir, "..", ".local-data");
    await mkdir(localDataDir, { recursive: true });
    tmpDir = await mkdtemp(join(localDataDir, "express-codegen-"));
    const modulePath = join(tmpDir, "books.router.ts");
    await writeFile(modulePath, evalSource, "utf8");
    const mod = (await import(pathToFileURL(modulePath).href)) as {
      createBooksRouter: (handlers: unknown) => Router;
    };

    // Wire the same handler functions the fixture tree's leaves already
    // carry, so the generated `Handlers` shape lines up with the authored
    // tree with no adaptation. Handler leaves are `{ handler, meta }` in the
    // raw Node tree; `unwrap` pulls the callable out.
    type LooseNode = {
      readonly children?: Record<string, LooseNode>;
      readonly fallback?: { readonly subtree: LooseNode };
      readonly handler?: unknown;
    };
    const root = evalTree as unknown as LooseNode;
    const unwrap = (n: LooseNode | undefined): unknown => n?.handler;
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const books = root.children!.books!;
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const bookItem = books.fallback!.subtree;
    const handlers = {
      books: {
        list: unwrap(books.children?.list),
        add: unwrap(books.children?.add),
        bookId: {
          read: unwrap(bookItem.children?.read),
          replace: unwrap(bookItem.children?.replace),
          remove: unwrap(bookItem.children?.remove),
        },
      },
    };

    const app: Express = express();
    app.use(express.json());
    app.use(mod.createBooksRouter(handlers as never));
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
      res.status(err.message.startsWith("Not Found") ? 404 : 500).json({ error: err.message });
    });

    server = app.listen(0);
    await new Promise<void>((resolve) => server?.once("listening", () => resolve()));
    const address = server.address();
    if (address === null || typeof address === "string")
      throw new Error("expected a bound TCP address");
    baseUrl = `http://localhost:${address.port}`;

    store.clear();
  });

  afterAll(async () => {
    await new Promise<void>((resolve) => server?.close(() => resolve()));
    if (tmpDir !== undefined) await rm(tmpDir, { recursive: true, force: true });
  });

  it("POST /books/add creates a book (real body-parsed JSON in, JSON out)", async () => {
    const res = await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Dune", author: "Herbert" }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.title).toBe("Dune");
    expect(body.id).toMatch(/^book-/);
  });

  it("GET /books/list lists created books", async () => {
    await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Foundation", author: "Asimov" }),
    });
    const res = await fetch(`${baseUrl}/books/list`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book[];
    expect(body.some((b) => b.title === "Foundation")).toBe(true);
  });

  it("GET /books/list?author=... merges real Express query params into handler input", async () => {
    await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Only Asimov", author: "Asimov" }),
    });
    const res = await fetch(`${baseUrl}/books/list?author=Asimov`);
    const body = (await res.json()) as Book[];
    expect(body.length).toBeGreaterThan(0);
    expect(body.every((b) => b.author === "Asimov")).toBe(true);
  });

  it("GET /books/:bookId resolves the real Express path param into handler input", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Neuromancer", author: "Gibson" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.id).toBe(created.id);
    expect(body.title).toBe("Neuromancer");
  });

  it("PUT /books/:bookId replaces via the co-located handler at the same path", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Snow Crash", author: "Stephenson" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Snow Crash (revised)", author: "Stephenson" }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.title).toBe("Snow Crash (revised)");
  });

  it("DELETE /books/:bookId removes via the co-located handler", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "To Delete", author: "X" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`, { method: "DELETE" });
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({ deleted: true });

    const after = await fetch(`${baseUrl}/books/${created.id}`);
    expect(after.status).toBe(404);
  });

  it("thrown handler errors reach next(err) and the app's own error middleware", async () => {
    const res = await fetch(`${baseUrl}/books/does-not-exist`);
    expect(res.status).toBe(404);
    const body = (await res.json()) as { error: string };
    expect(body.error).toContain("Not Found");
  });
});
