// packages/http-framework-projector/src/fastify.test.ts — Fastify router codegen tests
//
// Same three-part coverage shape as express.test.ts:
//   1. Structural: assert the generated source string has the expected
//      shape (imports, path syntax, Handlers type, factory function,
//      generated `schema` options) for a self-contained fixture tree.
//   2. Eval (end-to-end): write the generated source to a temp file, import
//      it as a real module, register the returned `FastifyPluginAsync` on a
//      real `fastify()` instance, and drive real HTTP requests at it via raw
//      `fetch` against a listening server, confirming the emitted code
//      works as an actual Fastify plugin and that Fastify's own native
//      JSON-Schema validation (the `schema.body`/`querystring`/`params`/
//      `response` options this codegen emits) runs against real requests.
//   3. HttpRoute-driven (no Node): `generateFastifyRoutes(route, schemas)`
//      called directly, exercising the core entry point standalone.

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import Fastify from "fastify";
import type { FastifyError, FastifyInstance } from "fastify";
import { api as api_, op } from "@rhi-zone/fractal-api-tree/node";
import { extractToolSchemas } from "@rhi-zone/fractal-api-tree/tree";
import type { SchemaMap } from "@rhi-zone/fractal-api-tree/tree";
import { http } from "@rhi-zone/fractal-http-api-projector/verbs";
import { httpProjection } from "@rhi-zone/fractal-http-api-projector/dx";
import { generateFastifyRoutes, generateFastifyRoutesFromNode } from "./fastify.ts";

// ============================================================================
// Fixture tree — same books list/add + per-book fallback (read/replace/remove
// co-located trio) shape express.test.ts uses, for the same reason (real
// path-param + co-location coverage).
// ============================================================================

type Book = { readonly id: string; readonly title: string; readonly author: string };

function makeStore() {
  const store = new Map<string, Book>();
  let seq = 0;

  const listBooks = op((input: { readonly author?: string }): Book[] => {
    const all = [...store.values()];
    return input?.author !== undefined ? all.filter((b) => b.author === input.author) : all;
  }, http.get);

  const addBook = op((input: { readonly title: string; readonly author: string }): Book => {
    const id = `book-${++seq}`;
    const book: Book = { id, ...input };
    store.set(id, book);
    return book;
  }, http.post);

  const readBook = op(
    (input: { readonly bookId: string }): Book => {
      const book = store.get(input.bookId);
      if (book === undefined) throw new Error(`Not Found: ${input.bookId}`);
      return book;
    },
    http.get,
    http.moveTo(".."),
  );

  const replaceBook = op(
    (input: { readonly bookId: string; readonly title: string; readonly author: string }): Book => {
      const book: Book = { id: input.bookId, title: input.title, author: input.author };
      store.set(input.bookId, book);
      return book;
    },
    http.put,
    http.moveTo(".."),
  );

  const removeBook = op(
    (input: { readonly bookId: string }): { readonly deleted: boolean } => {
      return { deleted: store.delete(input.bookId) };
    },
    http.delete,
    http.moveTo(".."),
  );

  const bookItemNode = api_({ read: readBook, replace: replaceBook, remove: removeBook });
  const booksNode = api_(
    { list: listBooks, add: addBook },
    { fallback: { name: "bookId", subtree: bookItemNode } },
  );
  const tree = api_({ books: booksNode });

  return { tree, store };
}

const { tree } = makeStore();
const treePath = new URL("./__fixtures__/fastify-tree.ts", import.meta.url).pathname;

let source: string;
let schemas: SchemaMap;

beforeAll(() => {
  schemas = extractToolSchemas(treePath);
  source = generateFastifyRoutesFromNode(tree, schemas, { routerName: "Books" });
});

// ============================================================================
// 1. Structural assertions
// ============================================================================

describe("generateFastifyRoutesFromNode — structure", () => {
  it("emits a generated/eject header", () => {
    expect(source).toMatch(/^\/\/ @generated by @rhi-zone\/fractal-http-framework-projector/);
    expect(source).toContain("Eject model");
  });

  it("imports FastifyPluginAsync (type-only) from fastify", () => {
    expect(source).toContain('import type { FastifyPluginAsync } from "fastify"');
  });

  it("emits real Fastify path syntax (:bookId, not {bookId})", () => {
    expect(source).toContain('"/books/:bookId"');
    expect(source).not.toContain("{bookId}");
  });

  it("emits GET for list, POST for add, GET/PUT/DELETE co-located at :bookId", () => {
    expect(source).toMatch(/fastify\.get\("\/books\/list",/);
    expect(source).toMatch(/fastify\.post\("\/books\/add",/);
    expect(source).toMatch(/fastify\.get\("\/books\/:bookId",/);
    expect(source).toMatch(/fastify\.put\("\/books\/:bookId",/);
    expect(source).toMatch(/fastify\.delete\("\/books\/:bookId",/);
  });

  it("emits the BooksHandlers type and createBooksRoutes factory returning FastifyPluginAsync", () => {
    expect(source).toContain("export type BooksHandlers");
    expect(source).toContain(
      "export function createBooksRoutes(handlers: BooksHandlers): FastifyPluginAsync",
    );
  });

  it("emits Input/Output type aliases from the schema map", () => {
    expect(source).toContain("export type BooksAddInput");
    expect(source).toContain("export type BooksAddOutput");
  });

  it("dispatches to the accumulated dotted handler path and returns its result directly", () => {
    expect(source).toContain("return await handlers.books.list(input)");
    expect(source).toContain("return await handlers.books.add(input)");
    expect(source).toContain("return await handlers.books.bookId.read(input)");
    expect(source).toContain("return await handlers.books.bookId.replace(input)");
    expect(source).toContain("return await handlers.books.bookId.remove(input)");
  });

  it("emits a native Fastify `schema` option splitting body vs params for POST /books/add", () => {
    expect(source).toMatch(/fastify\.post\("\/books\/add",\s*\{\s*\n\s*schema:\s*\{\s*\n\s*body:/);
    expect(source).toContain('"title"');
    expect(source).toContain('"author"');
  });

  it("emits a `params` schema (not `querystring`) for the bookId path param on GET /books/:bookId", () => {
    // The whole input to readBook is just { bookId }, and bookId is a path
    // param — so it should land entirely in `params`, with no leftover
    // `querystring` schema for this operation.
    const getBookIdBlock = source.slice(source.indexOf('fastify.get("/books/:bookId"'));
    const nextRoute = getBookIdBlock.indexOf("fastify.", 1);
    const block = getBookIdBlock.slice(0, nextRoute === -1 ? undefined : nextRoute);
    expect(block).toContain("params:");
    expect(block).toContain('"bookId"');
  });

  it("emits a `response` schema keyed by 200", () => {
    expect(source).toContain("response: { 200:");
  });
});

// ============================================================================
// 2. HttpRoute-driven entry point (no Node) — degraded naming
// ============================================================================

describe("generateFastifyRoutes — HttpRoute-driven, no Node", () => {
  it("still produces a mountable plugin factory with degraded (lowercased-verb) member names", () => {
    const route = httpProjection(tree);
    const routeSource = generateFastifyRoutes(route, schemas, { routerName: "Degraded" });
    expect(routeSource).toContain("export function createDegradedRoutes");
    expect(routeSource).toMatch(/return await handlers\.books\.bookId\.get\(input\)/);
    expect(routeSource).toMatch(/return await handlers\.books\.bookId\.put\(input\)/);
    expect(routeSource).toMatch(/return await handlers\.books\.bookId\.delete\(input\)/);
  });
});

// ============================================================================
// 3. Eval: real Fastify app, real HTTP requests
// ============================================================================

describe("generated Fastify routes — real app, real requests", () => {
  let tmpDir: string | undefined;
  let app: FastifyInstance | undefined;
  let baseUrl: string;

  beforeAll(async () => {
    const { tree: evalTree, store } = makeStore();
    const evalSchemas = extractToolSchemas(treePath);
    const evalSource = generateFastifyRoutesFromNode(evalTree, evalSchemas, {
      routerName: "Books",
    });

    // Written under the package's own `.local-data/` (gitignored) rather
    // than the OS tmpdir, same reason express.test.ts documents: the
    // generated file `import type`s "fastify", and module resolution walks
    // up from the importing file's directory looking for `node_modules`.
    const localDataDir = join(import.meta.dir, "..", ".local-data");
    await mkdir(localDataDir, { recursive: true });
    tmpDir = await mkdtemp(join(localDataDir, "fastify-codegen-"));
    const modulePath = join(tmpDir, "books.routes.ts");
    await writeFile(modulePath, evalSource, "utf8");
    const mod = (await import(pathToFileURL(modulePath).href)) as {
      createBooksRoutes: (handlers: unknown) => (fastify: FastifyInstance) => Promise<void>;
    };

    // Wire the same handler functions the fixture tree's leaves already
    // carry — same unwrap approach express.test.ts uses.
    type LooseNode = {
      readonly children?: Record<string, LooseNode>;
      readonly fallback?: { readonly subtree: LooseNode };
      readonly handler?: unknown;
    };
    const root = evalTree as unknown as LooseNode;
    const unwrap = (n: LooseNode | undefined): unknown => n?.handler;
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const books = root.children!.books!;
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const bookItem = books.fallback!.subtree;
    const handlers = {
      books: {
        list: unwrap(books.children?.list),
        add: unwrap(books.children?.add),
        bookId: {
          read: unwrap(bookItem.children?.read),
          replace: unwrap(bookItem.children?.replace),
          remove: unwrap(bookItem.children?.remove),
        },
      },
    };

    app = Fastify();
    app.setErrorHandler((err: FastifyError, _request, reply) => {
      const status = err.message.startsWith("Not Found") ? 404 : (err.statusCode ?? 500);
      reply.status(status).send({ error: err.message });
    });
    await app.register(mod.createBooksRoutes(handlers as never));
    baseUrl = await app.listen({ port: 0, host: "127.0.0.1" });

    store.clear();
  });

  afterAll(async () => {
    await app?.close();
    if (tmpDir !== undefined) await rm(tmpDir, { recursive: true, force: true });
  });

  it("POST /books/add creates a book (real schema-validated JSON in, JSON out)", async () => {
    const res = await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Dune", author: "Herbert" }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.title).toBe("Dune");
    expect(body.id).toMatch(/^book-/);
  });

  it("POST /books/add with a missing required field is rejected by Fastify's own generated schema validation (400, handler never runs)", async () => {
    const res = await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "No Author" }),
    });
    expect(res.status).toBe(400);
  });

  it("GET /books/list lists created books", async () => {
    await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Foundation", author: "Asimov" }),
    });
    const res = await fetch(`${baseUrl}/books/list`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book[];
    expect(body.some((b) => b.title === "Foundation")).toBe(true);
  });

  it("GET /books/list?author=... merges real Fastify query params into handler input", async () => {
    await fetch(`${baseUrl}/books/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Only Asimov", author: "Asimov" }),
    });
    const res = await fetch(`${baseUrl}/books/list?author=Asimov`);
    const body = (await res.json()) as Book[];
    expect(body.length).toBeGreaterThan(0);
    expect(body.every((b) => b.author === "Asimov")).toBe(true);
  });

  it("GET /books/:bookId resolves the real Fastify path param into handler input", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Neuromancer", author: "Gibson" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.id).toBe(created.id);
    expect(body.title).toBe("Neuromancer");
  });

  it("PUT /books/:bookId replaces via the co-located handler at the same path", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "Snow Crash", author: "Stephenson" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: "Snow Crash (revised)", author: "Stephenson" }),
    });
    expect(res.status).toBe(200);
    const body = (await res.json()) as Book;
    expect(body.title).toBe("Snow Crash (revised)");
  });

  it("DELETE /books/:bookId removes via the co-located handler", async () => {
    const created = (await (
      await fetch(`${baseUrl}/books/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "To Delete", author: "X" }),
      })
    ).json()) as Book;

    const res = await fetch(`${baseUrl}/books/${created.id}`, { method: "DELETE" });
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({ deleted: true });

    const after = await fetch(`${baseUrl}/books/${created.id}`);
    expect(after.status).toBe(404);
  });

  it("thrown handler errors reach Fastify's own error handler (not Express-style next(err))", async () => {
    const res = await fetch(`${baseUrl}/books/does-not-exist`);
    expect(res.status).toBe(404);
    const body = (await res.json()) as { error: string };
    expect(body.error).toContain("Not Found");
  });
});
